#!/usr/bin/env python3
"""Generate a nextpnr --pre-place BEL lock script from extracted packed-cell BEL locks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any
import re


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a nextpnr Python pre-place BEL lock script."
    )
    parser.add_argument("--locks-json", required=True, type=Path, action="append")
    parser.add_argument("--out-py", required=True, type=Path)
    parser.add_argument(
        "--scope",
        action="append",
        default=[],
        help="Optional scope filter. Repeatable; keeps only matching lock scopes.",
    )
    parser.add_argument(
        "--type",
        action="append",
        default=[],
        help="Optional type filter. Repeatable; keeps only matching lock types.",
    )
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Generated hook warns instead of failing if a locked cell is absent.",
    )
    parser.add_argument(
        "--skip-cell",
        action="append",
        default=[],
        help="Skip a lock by source or remapped cell name. Repeatable.",
    )
    parser.add_argument(
        "--ypcb-wrapper-remap",
        action="store_true",
        help="Remap LLM2FPGA v40 YPCB lock cell names to this repo's YPCB wrapper names.",
    )
    parser.add_argument(
        "--ypcb-top",
        default="ypcb_00338_1p1_uberddr3_bist",
        help="YPCB top module name used when remapping synthesized I/O buffer cells.",
    )
    args = parser.parse_args()

    lock_docs = [load_json(path) for path in args.locks_json]
    requested_scopes = set(args.scope)
    requested_types = set(args.type)
    skipped_cells = set(args.skip_cell)

    def keep_lock(lock: dict[str, Any]) -> bool:
        if requested_scopes and str(lock.get("scope", "")) not in requested_scopes:
            return False
        if requested_types and str(lock.get("type", "")) not in requested_types:
            return False
        return True

    def remap_cell_name(name: str) -> str:
        if not args.ypcb_wrapper_remap:
            return name
        if name.startswith("uberddr3."):
            return "bist_top." + name
        if name in {
            "clk100_90_bufg",
            "clk100_bufg",
            "clk200_bufg",
            "clk25_bufg",
            "clock_pll",
        }:
            return "bist_top." + name

        def vector_port(port: str, index: str) -> str:
            suffix = "" if index == "0" else "_" + index
            return f"$iopadmap${args.ypcb_top}.{port}{suffix}"

        vector_match = re.fullmatch(
            r"ddram_(a|ba)\[(\d+)\]\$obuf\$\$intcell\$OBUF", name
        )
        if vector_match:
            kind, index = vector_match.groups()
            port = "ddr3_addr" if kind == "a" else "ddr3_ba"
            return vector_port(port, index)

        scalar_match = re.fullmatch(r"ddram_([a-z0-9_]+)\$obuf\$\$intcell\$OBUF", name)
        if scalar_match:
            signal = scalar_match.group(1)
            signal_map = {
                "cas_n": "ddr3_cas_n",
                "cke": "ddr3_cke",
                "cs_n": "ddr3_cs_n",
                "odt": "ddr3_odt",
                "ras_n": "ddr3_ras_n",
                "reset_n": "ddr3_reset_n",
                "we_n": "ddr3_we_n",
            }
            if signal in signal_map:
                return f"$iopadmap${args.ypcb_top}.{signal_map[signal]}"
        return name

    locks = []
    for locks_doc in lock_docs:
        for lock in locks_doc["locks"]:
            if not keep_lock(lock):
                continue
            remapped = dict(lock)
            remapped["source_cell"] = lock["cell"]
            remapped["cell"] = remap_cell_name(str(lock["cell"]))
            if lock["cell"] in skipped_cells or remapped["cell"] in skipped_cells:
                continue
            locks.append(remapped)
    if requested_scopes and not locks:
        raise SystemExit(
            "no BEL locks matched requested scopes: " + ", ".join(sorted(requested_scopes))
        )
    allow_missing = "True" if args.allow_missing else "False"
    script = f'''# Generated by scripts/task6/generate_nextpnr_pre_place_bel_locks.py.
# Runs under nextpnr-xilinx --pre-place after packing and before placement.

LOCKS = {json.dumps(locks, indent=2, sort_keys=True)}
ALLOW_MISSING = {allow_missing}

applied = 0
missing = []
conflicts = []

for lock in LOCKS:
    name = lock["cell"]
    bel = lock["bel"]
    if name not in ctx.cells:
        missing.append(lock)
        continue
    cell = ctx.cells[name]
    existing_bel = cell.attrs["BEL"] if "BEL" in cell.attrs else None
    if existing_bel is not None and str(existing_bel) != bel:
        conflicts.append({{
            "cell": name,
            "type": lock.get("type", ""),
            "old_bel": str(existing_bel),
            "new_bel": bel,
        }})
        continue
    cell.setAttr("BEL", bel)
    applied += 1

if conflicts:
    raise RuntimeError("Task 6 pre-place BEL lock conflicts: " + repr(conflicts[:16]))
if missing and not ALLOW_MISSING:
    raise RuntimeError("Task 6 pre-place BEL lock missing cells: " + repr(missing[:16]))

print(
    "Task 6 pre-place BEL locks: applied={{}} missing={{}} source={','.join(str(path) for path in args.locks_json)}"
    .format(applied, len(missing))
)
if missing and ALLOW_MISSING:
    print("Task 6 pre-place BEL missing sample: " + repr(missing[:16]))
'''
    args.out_py.write_text(script, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
