#!/usr/bin/env python3
"""Generate the Verilog step ROM for the YPCB PHASER byte-lane sequencer."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SCHEMA = "ypcb-phaser-byte-lane-sequence-v1"
FLAG_FIELDS = (
    "phaser_ref_pwrdwn",
    "phaser_ref_rst",
    "phyctl_reset",
    "readcalibenable",
    "writecalibenable",
    "phyctlwrenable",
    "lane_reset",
    "rstdqsfind",
    "sync_enable",
)
WAIT_FIELDS = (
    "pll_locked",
    "phaser_ref_locked",
    "in_phase_locked",
    "phyctl_ready",
)


def parse_int(value: Any, *, bits: int, field_name: str) -> int:
    if isinstance(value, int):
        result = value
    elif isinstance(value, str):
        result = int(value, 0)
    else:
        raise ValueError(f"{field_name} must be an int or string, got {type(value).__name__}")
    if result < 0 or result >= (1 << bits):
        raise ValueError(f"{field_name} must fit in {bits} bits")
    return result


def parse_bool(value: Any, *, field_name: str) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return bool(value)
    if isinstance(value, str):
        text = value.strip().lower()
        if text in {"1", "true", "yes", "on"}:
            return True
        if text in {"0", "false", "no", "off"}:
            return False
    raise ValueError(f"{field_name} must be a boolean-like value")


def encode_flags(controls: dict[str, bool], names: tuple[str, ...]) -> int:
    value = 0
    for bit_index, field_name in enumerate(names):
        if controls.get(field_name, False):
            value |= 1 << bit_index
    return value


def validate_step(step: dict[str, Any], *, index: int) -> dict[str, Any]:
    if not isinstance(step, dict):
        raise ValueError(f"step {index} must be an object")

    controls = step.get("controls", {})
    if not isinstance(controls, dict):
        raise ValueError(f"step {index} controls must be an object")
    normalized_controls = {
        field_name: parse_bool(
            controls.get(field_name, False),
            field_name=f"steps[{index}].controls.{field_name}",
        )
        for field_name in FLAG_FIELDS
    }

    wait_for = step.get("wait_for", [])
    if not isinstance(wait_for, list):
        raise ValueError(f"step {index} wait_for must be a list")
    wait_set = set()
    for item in wait_for:
        if item not in WAIT_FIELDS:
            raise ValueError(
                f"step {index} wait_for contains unknown signal {item!r}; "
                f"expected one of {', '.join(WAIT_FIELDS)}"
            )
        wait_set.add(item)

    dwell_cycles = parse_int(step.get("dwell_cycles", 1), bits=16, field_name=f"steps[{index}].dwell_cycles")
    if dwell_cycles == 0:
        raise ValueError(f"step {index} dwell_cycles must be at least 1")

    return {
        "name": str(step.get("name", f"step_{index}")),
        "dwell_cycles": dwell_cycles,
        "controls": normalized_controls,
        "wait_for": tuple(field_name for field_name in WAIT_FIELDS if field_name in wait_set),
        "phyctlwd": parse_int(step.get("phyctlwd", 0), bits=32, field_name=f"steps[{index}].phyctlwd"),
    }


def load_spec(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("schema") != SCHEMA:
        raise ValueError(f"expected schema {SCHEMA!r}, got {payload.get('schema')!r}")

    steps = payload.get("steps")
    if not isinstance(steps, list) or not steps:
        raise ValueError("sequence spec must contain at least one step")

    return {
        "schema": payload["schema"],
        "name": str(payload.get("name", path.stem)),
        "clock_domain": str(payload.get("clock_domain", "clk50")),
        "final_step_hold": parse_bool(
            payload.get("final_step_hold", True),
            field_name="final_step_hold",
        ),
        "steps": [validate_step(step, index=index) for index, step in enumerate(steps)],
    }


def render_header(spec: dict[str, Any], *, source: str) -> str:
    last_step = spec["steps"][-1]
    lines = [
        "// Auto-generated by scripts/task6/generate_ypcb_phaser_sequence_header.py",
        f"// Source: {source}",
        f"// Sequence: {spec['name']}",
        f"// Clock domain: {spec['clock_domain']}",
        "//",
        "// Flag bits:",
    ]
    for bit_index, field_name in enumerate(FLAG_FIELDS):
        lines.append(f"//   [{bit_index}] {field_name}")
    lines.append("// Wait bits:")
    for bit_index, field_name in enumerate(WAIT_FIELDS):
        lines.append(f"//   [{bit_index}] {field_name}")
    lines.extend(
        [
            f"localparam integer PHASER_SEQUENCE_STEP_COUNT = {len(spec['steps'])};",
            (
                "localparam [0:0] PHASER_SEQUENCE_FINAL_HOLD = "
                f"1'b{1 if spec['final_step_hold'] else 0};"
            ),
            "",
            "function [15:0] phaser_sequence_hold_cycles;",
            "    input [7:0] idx;",
            "    begin",
            "        case (idx)",
        ]
    )
    for index, step in enumerate(spec["steps"]):
        lines.append(f"            8'd{index}: phaser_sequence_hold_cycles = 16'd{step['dwell_cycles']}; // {step['name']}")
    lines.extend(
        [
            f"            default: phaser_sequence_hold_cycles = 16'd{last_step['dwell_cycles']};",
            "        endcase",
            "    end",
            "endfunction",
            "",
            f"function [{len(FLAG_FIELDS) - 1}:0] phaser_sequence_flags;",
            "    input [7:0] idx;",
            "    begin",
            "        case (idx)",
        ]
    )
    for index, step in enumerate(spec["steps"]):
        encoded = encode_flags(step["controls"], FLAG_FIELDS)
        lines.append(
            f"            8'd{index}: phaser_sequence_flags = {len(FLAG_FIELDS)}'h{encoded:0{(len(FLAG_FIELDS) + 3) // 4}x}; // {step['name']}"
        )
    last_flags = encode_flags(last_step["controls"], FLAG_FIELDS)
    lines.extend(
        [
            f"            default: phaser_sequence_flags = {len(FLAG_FIELDS)}'h{last_flags:0{(len(FLAG_FIELDS) + 3) // 4}x};",
            "        endcase",
            "    end",
            "endfunction",
            "",
            f"function [{len(WAIT_FIELDS) - 1}:0] phaser_sequence_wait_flags;",
            "    input [7:0] idx;",
            "    begin",
            "        case (idx)",
        ]
    )
    for index, step in enumerate(spec["steps"]):
        encoded = encode_flags({field_name: field_name in step["wait_for"] for field_name in WAIT_FIELDS}, WAIT_FIELDS)
        lines.append(
            f"            8'd{index}: phaser_sequence_wait_flags = {len(WAIT_FIELDS)}'h{encoded:x}; // {step['name']}"
        )
    last_wait = encode_flags({field_name: field_name in last_step["wait_for"] for field_name in WAIT_FIELDS}, WAIT_FIELDS)
    lines.extend(
        [
            f"            default: phaser_sequence_wait_flags = {len(WAIT_FIELDS)}'h{last_wait:x};",
            "        endcase",
            "    end",
            "endfunction",
            "",
            "function [31:0] phaser_sequence_phyctlwd;",
            "    input [7:0] idx;",
            "    begin",
            "        case (idx)",
        ]
    )
    for index, step in enumerate(spec["steps"]):
        lines.append(
            f"            8'd{index}: phaser_sequence_phyctlwd = 32'h{step['phyctlwd']:08x}; // {step['name']}"
        )
    lines.extend(
        [
            f"            default: phaser_sequence_phyctlwd = 32'h{last_step['phyctlwd']:08x};",
            "        endcase",
            "    end",
            "endfunction",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    spec = load_spec(args.spec)
    rendered = render_header(spec, source=str(args.spec))
    args.out.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
