#!/usr/bin/env python3
"""Generate a nextpnr --pre-place script from extracted BEL locks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locks-json", required=True, type=Path)
    parser.add_argument("--out-py", required=True, type=Path)
    parser.add_argument("--allow-missing", action="store_true")
    args = parser.parse_args()

    locks = load_json(args.locks_json)["locks"]
    allow_missing = "True" if args.allow_missing else "False"
    script = f'''# Generated by generate_nextpnr_pre_place_bel_locks.py.
# Runs under nextpnr-xilinx --pre-place after packing and before placement.

LOCKS = {json.dumps(locks, indent=2, sort_keys=True)}
ALLOW_MISSING = {allow_missing}

applied = 0
missing = []
conflicts = []

for lock in LOCKS:
    name = lock["cell"]
    bel = lock["bel"]
    if name not in ctx.cells:
        missing.append(lock)
        continue
    cell = ctx.cells[name]
    existing_bel = cell.attrs["BEL"] if "BEL" in cell.attrs else None
    if existing_bel is not None and str(existing_bel) != bel:
        conflicts.append({{
            "cell": name,
            "type": lock.get("type", ""),
            "old_bel": str(existing_bel),
            "new_bel": bel,
        }})
        continue
    cell.setAttr("BEL", bel)
    applied += 1

if conflicts:
    raise RuntimeError("YPCB pre-place BEL lock conflicts: " + repr(conflicts[:16]))
if missing and not ALLOW_MISSING:
    raise RuntimeError("YPCB pre-place BEL lock missing cells: " + repr(missing[:16]))

print("YPCB pre-place BEL locks: applied={{}} missing={{}} source={args.locks_json}".format(applied, len(missing)))
'''
    args.out_py.write_text(script, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
