#!/usr/bin/env python3
"""Generate a nextpnr --pre-place script from extracted BEL locks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locks-json", required=True, type=Path)
    parser.add_argument("--out-py", required=True, type=Path)
    parser.add_argument("--allow-missing", action="store_true")
    args = parser.parse_args()

    locks = load_json(args.locks_json)["locks"]
    allow_missing = "True" if args.allow_missing else "False"
    script = f'''# Generated by generate_nextpnr_pre_place_bel_locks.py.
# Runs under nextpnr-xilinx --pre-place after packing and before placement.

LOCKS = {json.dumps(locks, indent=2, sort_keys=True)}
ALLOW_MISSING = {allow_missing}

applied = 0
missing = []
conflicts = []
ambiguous = []


def lock_suffix(name):
    separator = chr(92)
    if separator in name:
        return name.split(separator, 1)[1]
    return name


def resolve_cell(lock):
    name = lock["cell"]
    if name in ctx.cells:
        return name, ctx.cells[name]
    suffix = lock.get("cell_suffix", lock_suffix(name))
    matches = [(str(candidate), candidate_cell) for candidate, candidate_cell in ctx.cells if str(candidate).endswith(suffix)]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        ambiguous.append({{
            "cell": name,
            "suffix": suffix,
            "matches": matches[:16],
        }})
    return name, None


for lock in LOCKS:
    name, cell = resolve_cell(lock)
    bel = lock["bel"]
    if cell is None:
        missing.append(lock)
        continue
    existing_bel = str(cell.bel)
    if existing_bel in ("", "None"):
        existing_bel = None
    if existing_bel is not None and existing_bel != bel:
        conflicts.append({{
            "cell": name,
            "type": lock.get("type", ""),
            "old_bel": existing_bel,
            "new_bel": bel,
        }})
        continue
    if existing_bel is None and not ctx.checkBelAvail(bel):
        conflicts.append({{
            "cell": name,
            "type": lock.get("type", ""),
            "old_bel": "occupied",
            "new_bel": bel,
        }})
        continue
    if existing_bel is None:
        ctx.bindBel(bel, cell, STRENGTH_USER)
    applied += 1

if conflicts:
    raise RuntimeError("YPCB pre-place BEL lock conflicts: " + repr(conflicts[:16]))
if ambiguous:
    raise RuntimeError("YPCB pre-place BEL lock ambiguous cells: " + repr(ambiguous[:16]))
if missing and not ALLOW_MISSING:
    raise RuntimeError("YPCB pre-place BEL lock missing cells: " + repr(missing[:16]))

print("YPCB pre-place BEL locks: applied={{}} missing={{}} source={args.locks_json}".format(applied, len(missing)))
'''
    args.out_py.write_text(script, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
