#!/usr/bin/env python3
"""Run YPCB DDR3 board tests for each row in a build manifest.

Expected CSV columns: experiment_id, seed, variant, bitstream_file.
"""

from __future__ import annotations

import argparse
import csv
import subprocess
from pathlib import Path

STATUS_FIELDS = ["experiment_id", "seed", "variant", "bitstream", "result_json", "log", "returncode", "status"]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_status(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=STATUS_FIELDS, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in STATUS_FIELDS})


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("local-artifacts/board-sweeps"))
    parser.add_argument("--board-test", type=Path, default=Path("example_demo/ypcb_00338_1p1/scripts/ypcb_ddr3_board_test.py"))
    parser.add_argument("--poll-count", type=int, default=100)
    parser.add_argument("--poll-interval", type=float, default=0.1)
    parser.add_argument("--skip-existing", action="store_true")
    parser.add_argument("--continue-on-fail", action="store_true")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    status_path = args.out_dir / "sweep_status.csv"
    status_rows: list[dict[str, object]] = []
    final_rc = 0

    for row in read_csv(args.manifest):
        experiment_id = row["experiment_id"]
        result_json = args.out_dir / f"{experiment_id}.json"
        log_path = args.out_dir / f"{experiment_id}.log"
        bitstream = row["bitstream_file"]

        if args.skip_existing and result_json.exists():
            status_rows.append({"experiment_id": experiment_id, "seed": row.get("seed", ""), "variant": row.get("variant", ""), "bitstream": bitstream, "result_json": result_json, "log": log_path, "returncode": "", "status": "skipped_existing"})
            write_status(status_path, status_rows)
            continue

        command = ["python3", str(args.board_test), "--bitstream", bitstream, "--output", str(result_json), "--poll-count", str(args.poll_count), "--poll-interval", str(args.poll_interval)]
        completed = subprocess.run(command, check=False, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        log_path.write_text(completed.stdout, encoding="utf-8")
        status = "pass" if completed.returncode == 0 else "fail"
        status_rows.append({"experiment_id": experiment_id, "seed": row.get("seed", ""), "variant": row.get("variant", ""), "bitstream": bitstream, "result_json": result_json, "log": log_path, "returncode": completed.returncode, "status": status})
        write_status(status_path, status_rows)
        print(f"{experiment_id}: {status} rc={completed.returncode}")
        if completed.returncode != 0:
            final_rc = completed.returncode
            if not args.continue_on_fail:
                break

    (args.out_dir / "README.md").write_text("\n".join(["# YPCB DDR3 Hardware Sweep", "", "Generated by `scripts/uberddr3_run_board_manifest.py`.", "", f"- manifest: `{args.manifest}`", f"- poll count: `{args.poll_count}`", f"- poll interval seconds: `{args.poll_interval}`", f"- rows attempted: `{len(status_rows)}`", f"- status CSV: `{status_path}`", ""]), encoding="utf-8")
    print(status_path)
    return final_rc


if __name__ == "__main__":
    raise SystemExit(main())
