# Autogenerated by LiteX / git: 5ad43630a
set -e
yosys  -l ypcb_00338_1p1.rpt ypcb_00338_1p1.ys
nextpnr-xilinx --json ypcb_00338_1p1.json --xdc ypcb_00338_1p1.xdc --fasm ypcb_00338_1p1.fasm --chipdb /tmp/ypcb-dfii-k7-generate/chipdb/xc7k480tffg1156.bin --write ypcb_00338_1p1_routed.json --timing-allow-fail --seed 1  --freq 200
fasm2frames --part xc7k480tffg1156-2 --db-root /nix/store/6naq2121dn4lq1axfp2a9x7jmr8f5fx0-prjxray-db-kintex7-lioi3-tbytesrc-oclkm/kintex7 ypcb_00338_1p1.fasm > ypcb_00338_1p1.frames 
xc7frames2bit --part_file /nix/store/6naq2121dn4lq1axfp2a9x7jmr8f5fx0-prjxray-db-kintex7-lioi3-tbytesrc-oclkm/kintex7/xc7k480tffg1156-2/part.yaml --part_name xc7k480tffg1156-2 --frm_file ypcb_00338_1p1.frames --output_file ypcb_00338_1p1.bit 
