set_property LOC AA28 [get_ports {clk50}]
set_property IOSTANDARD LVCMOS18 [get_ports {clk50}]
create_clock -name clk50 -period 20.000 [get_ports clk50]

set_property LOC R28 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_n}]

set_property LOC P30 [get_ports {led[0]}]
set_property LOC M30 [get_ports {led[1]}]
set_property LOC N30 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]

set_property LOC AG17 [get_ports {ddr3_dq[0]}]
set_property LOC AG16 [get_ports {ddr3_dq[1]}]
set_property LOC AH17 [get_ports {ddr3_dq[2]}]
set_property LOC AJ19 [get_ports {ddr3_dq[3]}]
set_property LOC AH18 [get_ports {ddr3_dq[4]}]
set_property LOC AH19 [get_ports {ddr3_dq[5]}]
set_property LOC AJ16 [get_ports {ddr3_dq[6]}]
set_property LOC AJ17 [get_ports {ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[7]}]
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dq[7]}]

set_property LOC AK16 [get_ports {ddr3_dqs_p}]
set_property LOC AK17 [get_ports {ddr3_dqs_n}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n}]
set_property SLEW FAST [get_ports {ddr3_dqs_p}]
set_property SLEW FAST [get_ports {ddr3_dqs_n}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dqs_p}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddr3_dqs_n}]
