// Auto-generated by scripts/task6/generate_ypcb_phaser_sequence_header.py
// Source: example_demo/ypcb_00338_1p1/ypcb_phaser_byte_lane_diag_sequence_observe_only.json
// Sequence: observe-only-open-parity
// Clock domain: clk50
//
// Flag bits:
//   [0] phaser_ref_pwrdwn
//   [1] phaser_ref_rst
//   [2] phyctl_reset
//   [3] readcalibenable
//   [4] writecalibenable
//   [5] phyctlwrenable
//   [6] lane_reset
//   [7] rstdqsfind
//   [8] sync_enable
// Wait bits:
//   [0] pll_locked
//   [1] phaser_ref_locked
//   [2] in_phase_locked
//   [3] phyctl_ready
localparam integer PHASER_SEQUENCE_STEP_COUNT = 1;
localparam [0:0] PHASER_SEQUENCE_FINAL_HOLD = 1'b1;

function [15:0] phaser_sequence_hold_cycles;
    input [7:0] idx;
    begin
        case (idx)
            8'd0: phaser_sequence_hold_cycles = 16'd1; // observe_only
            default: phaser_sequence_hold_cycles = 16'd1;
        endcase
    end
endfunction

function [8:0] phaser_sequence_flags;
    input [7:0] idx;
    begin
        case (idx)
            8'd0: phaser_sequence_flags = 9'h100; // observe_only
            default: phaser_sequence_flags = 9'h100;
        endcase
    end
endfunction

function [3:0] phaser_sequence_wait_flags;
    input [7:0] idx;
    begin
        case (idx)
            8'd0: phaser_sequence_wait_flags = 4'h0; // observe_only
            default: phaser_sequence_wait_flags = 4'h0;
        endcase
    end
endfunction

function [31:0] phaser_sequence_phyctlwd;
    input [7:0] idx;
    begin
        case (idx)
            8'd0: phaser_sequence_phyctlwd = 32'h00000000; // observe_only
            default: phaser_sequence_phyctlwd = 32'h00000000;
        endcase
    end
endfunction
